---
- hosts: hubs
  tags: install
  name: Install Docker
  roles:
    - geerlingguy.docker

- hosts: hubs
  tasks:

    - name: Install APT Dependencies
      tags: apt
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - git
        - libffi-dev
        - libssl-dev
        - nodejs-legacy
        - npm
        - python3-dev
        - python3-pip
        - python3-venv
        - supervisor
      become: yes
      become_user: root

    - name: Create JupyterHub User
      user:
        name: jupyterhub
        groups:
          - docker
        append: yes

    - name: Create JupyterHub src directory.
      tags: files
      file:
        path: ~/src
        state: directory
        mode: "u=rwx,g=r,o=r"
      become: yes
      become_user: jupyterhub

    - name: Copy local files to remote server.
      tags: files
      copy:
        src: files/{{ item }}
        dest: ~/src/{{ item }}
      with_items:
        - Dockerfile
        - jupyterhub_config.py
        - requirements.txt
      become: yes
      become_user: jupyterhub

    - name: Install Python Packages
      tags: virtualenv
      shell: python3 -m pip install -r ~/src/requirements.txt
      become: yes
      become_user: root

    - name: Install foo
      tags: npm
      npm:
        global: yes
        production: yes
        name: "configurable-http-proxy"
        version: 2.0.4
      become: yes
      become_user: root
